#!/bin/sh

arg=$1
[ -z $1 ] || shift

if [ -z $VIRTUAL_ENV ]; then
	dir=$(dirname $(readlink -f $0))
	python=$dir/.virtualenv/bin/python
else
	python=python
fi

if [ "$arg" = "-t" ] || [ "$arg" = "test" ] || [ "$arg" = "tests" ] || [ "$arg" = "tests/" ]; then
	$python -m unittest discover -s ./tests/ -p '*_test.py'
	exit $?
fi

if [ "$arg" = "-l" ] || [ "$arg" = "lint" ]; then
	module=${1-botologist plugins}
	[ -z $1 ] || shift

	$python -m pylint --rcfile=.pylintrc $@ $module
	exit $?
fi

$python -m botologist
exit $?
